import type { Audience } from "./types";
import { SALES_EMAIL } from "@/lib/site";

/**
 * "Who it's for" pages. Every claim must trace to docs/PRODUCT_FACTS.md.
 * Cost examples are computed on the page from copies × pages × the per-page price.
 */
export const AUDIENCES: Audience[] = [
  {
    slug: "schools",
    label: "Schools",
    icon: "School",
    title: "AI Answer Sheet Checking for Schools (CBSE, ICSE, State Boards)",
    description: "Check unit tests, half-yearly and pre-board copies with AI. Teachers upload the class's scans, review the marks and release red-pen checked copies to students.",
    eyebrow: "For schools",
    h1: "Give teachers their evenings back after every exam.",
    lede: "Unit tests, half-yearlies, pre-boards. Scan the class's copies, upload them in one go, and let Evalezy do the first check, in red pen, against one marking scheme. Teachers review, adjust and release.",
    pains: [
      { title: "Copies pile up after every exam", body: "A teacher with four sections can carry 150+ copies home after one paper. Checking eats evenings and weekends, and results go out late." },
      { title: "Marking drifts across checkers", body: "The same answer can get 2 marks from one teacher and 3 from another, or from the same teacher at copy 5 and copy 95." },
      { title: "Feedback stops at a number", body: "Under time pressure, students get a score and a few ticks. They rarely see why they lost marks on a long answer." },
    ],
    workflow: [
      { title: "Set the paper once", body: "Upload the question paper; it is read into questions with marks. Accept the AI-drafted marking scheme or type your own." },
      { title: "Scan and upload the whole section", body: "Phone photos or scanner PDFs, one file per student, up to 200 at a time. Names and roll numbers are read from the top of each copy and matched to the section." },
      { title: "Review on your own time", body: "Marks fill in question by question. Open any copy, read the extracted answer and feedback, change a mark if you disagree." },
      { title: "Release when you are ready", body: "Students see nothing until you press Release Result. Each student gets the checked copy as a PDF by email." },
    ],
    outcomes: [
      "Every copy marked against the same scheme, from the first to the last",
      "A note on every answer that lost marks, in red pen on the copy itself",
      "Teachers stay the final word: edited marks are never overwritten",
      "Unreadable scans are flagged for a re-scan, not guessed and not charged",
    ],
    example: { copies: 160, pages: 8, label: "four sections of 40, an 8-page half-yearly copy" },
    faqs: [
      { q: "Does it work for CBSE, ICSE and state-board papers?", a: "Yes. Evalezy marks against the questions and marking scheme you give it, so the board does not matter. Upload your paper, check the drafted scheme against your board's marking guidelines, and edit any criterion before you run the check." },
      { q: "Our teachers check in notebooks, not answer booklets. Will phone photos work?", a: "Yes. The sample copy on this site is a phone photo of a spiral notebook. Pages are straightened and cleaned before reading. Very dark, blurred or cut-off photos fail with a clear message and are not charged, so you can re-scan them." },
      { q: "Can students see marks before the teacher checks them?", a: "No. AI marks are a draft. Students see \"Results pending\" until a teacher presses Release Result, and that rule is enforced on the server, not just hidden in the app." },
      { q: "What does it cost a school?", a: "₹1 per page checked. A section of 40 students writing an 8-page copy costs ₹320 for that paper. Failed and unreadable copies are free." },
    ],
  },
  {
    slug: "coaching-institutes",
    label: "Coaching institutes",
    icon: "GraduationCap",
    title: "AI Copy Checking for Coaching Institutes and Test Series",
    description: "Weekly tests and test series checked overnight: bulk upload, automatic student matching, consistent marking and red-pen checked copies your students will read.",
    eyebrow: "For coaching institutes",
    h1: "Weekly tests, checked before the next class.",
    lede: "Your faculty should be teaching, not checking 300 copies after every Sunday test. Upload the batch, let Evalezy check it against one scheme, and send students a checked copy they can actually learn from.",
    pains: [
      { title: "Checking caps how often you can test", body: "More practice tests mean better results, but every test adds hundreds of copies to someone's desk. So tests get cut, or checking gets rushed." },
      { title: "Outsourced checkers are inconsistent", body: "Part-time evaluators mark differently, miss deadlines and need re-checking. Students notice when two friends get different marks for the same answer." },
      { title: "Parents and students want proof", body: "A mark sheet alone does not show improvement. A checked copy with notes shows exactly where marks were lost." },
    ],
    workflow: [
      { title: "Create the test once, reuse the scheme", body: "Upload the paper; the marking scheme is generated once per question and reused for every student in every batch." },
      { title: "Upload all batches in one go", body: "Up to 200 copies per upload. Each copy is matched to a student by name or roll number; anything unclear waits for you to pick." },
      { title: "Or let students upload", body: "If students submit photos of their answers in the online test, check every submitted copy with one click, or switch on auto-check on submit." },
      { title: "Release with a checked copy", body: "Release results and each student gets their checked copy by email. Connect WhatsApp in Automations to send results there too." },
    ],
    outcomes: [
      "Test more often without hiring more checkers",
      "One marking standard across batches, centres and faculty",
      "Checked copies students and parents can read line by line",
      "₹1 a page, so a 6-page test costs ₹6 a student",
    ],
    example: { copies: 300, pages: 6, label: "a 300-student weekly test, 6 pages a copy" },
    faqs: [
      { q: "Can we use our own model answers?", a: "Yes. Add a model answer per question, or replace the drafted marking scheme entirely. A stored model answer is used ahead of anything the AI generates." },
      { q: "We run the same test across several centres. Is the marking consistent?", a: "Yes, by design. The marking scheme for each question is created once and reused for every copy, at every centre, so the same answer is judged against the same criteria." },
      { q: "How fast is it?", a: "A copy usually takes 1 to 8 minutes and several copies are checked in parallel. The first results appear in about 10 minutes and 100 copies take roughly 2 to 3 hours. Upload in the evening and review in the morning." },
      { q: "Can students upload their own answer photos?", a: "Yes. In an online test set to manual evaluation, students upload their answer sheet as a PDF. You can check all submitted copies with one click, or have each one checked automatically as it is submitted." },
    ],
  },
  {
    slug: "upsc-answer-writing",
    label: "UPSC & PSC answer writing",
    icon: "PenLine",
    title: "AI Evaluation for UPSC Mains and State PSC Answer Writing",
    description: "Run daily answer-writing practice at scale: AI checks handwritten mains answers against your rubric, leaves margin notes on the copy, and mentors review before release.",
    eyebrow: "For UPSC & state PSC programs",
    h1: "Daily answer writing, with feedback on every answer.",
    lede: "Answer-writing programs live or die on feedback turnaround. Evalezy does the first evaluation of each handwritten answer against your rubric, writes the margin notes, and leaves the final word to your mentors.",
    pains: [
      { title: "Mentor time is the bottleneck", body: "Good evaluators are scarce and expensive. When enrolments grow, turnaround slips from two days to two weeks." },
      { title: "Feedback quality varies by evaluator", body: "Some mentors write detailed notes, some write \"good\". Aspirants compare copies and notice." },
      { title: "Aspirants need the why, not just the score", body: "\"6/15\" does not help. \"Introduction missing context; no examples for the second dimension\" does." },
    ],
    workflow: [
      { title: "Put your rubric in", body: "Write the criteria you already teach: introduction, dimensions covered, examples, conclusion. Or let Evalezy draft them and edit." },
      { title: "Aspirants upload their answers", body: "Scanned or photographed answer sheets, uploaded by the aspirant or in bulk by your team." },
      { title: "AI does the first evaluation", body: "Each answer is read and marked against your criteria, in half-mark steps, with a note on what was missing written on the copy." },
      { title: "Mentors review and release", body: "Mentors skim the AI's marks and notes, adjust where they disagree and release. Their edits are never overwritten." },
    ],
    outcomes: [
      "Feedback in hours, not weeks, even as batches grow",
      "Every answer judged on the same criteria",
      "Margin notes written on the aspirant's own copy",
      "Mentors spend time on judgement, not on reading every line",
    ],
    example: { copies: 500, pages: 4, label: "500 aspirants writing a 4-page daily answer" },
    faqs: [
      { q: "Can the AI judge a GS mains answer well?", a: "It judges the answer against the criteria you set: what must be covered, how marks split, what a strong answer includes. That is why we ask you to write or edit the rubric. Mentors should review the marks before release; they can change any mark in a few clicks." },
      { q: "Does it handle Hindi-medium answers?", a: "Evalezy is built and tested on English answer sheets today. If you run a Hindi-medium program, send us a few sample copies and we will tell you honestly how it does." },
      { q: "Can we keep our own evaluators in the loop?", a: "Yes. Nothing reaches the aspirant until someone on your team presses Release Result. Any mark a mentor edits is kept, even if the copy is checked again." },
    ],
  },
  {
    slug: "colleges-universities",
    label: "Colleges & universities",
    icon: "Landmark",
    title: "AI Answer Script Evaluation for Colleges and Universities",
    description: "Internal assessments and semester scripts checked against a fixed rubric, with faculty review before release. Consistent marking across evaluators and departments.",
    eyebrow: "For colleges & universities",
    h1: "Internal assessments without the marking backlog.",
    lede: "Mid-terms, internals and assignments arrive in hundreds of scripts per course. Evalezy does the first evaluation against your rubric and returns annotated scripts; faculty review, moderate and release.",
    pains: [
      { title: "Large classes, few evaluators", body: "A 240-student course with two faculty members means weeks of evaluation for every internal." },
      { title: "Moderation is slow", body: "Re-checking a sample of scripts for consistency is the first thing to go when deadlines bite." },
      { title: "Students dispute marks", body: "Without written feedback on the script, re-evaluation requests are hard to answer." },
    ],
    workflow: [
      { title: "Fix the rubric for the course", body: "Upload the paper and set the criteria per question. The same rubric is used for every script." },
      { title: "Bulk upload scripts", body: "Up to 200 scripts per upload, matched to enrolled students by name or roll number." },
      { title: "Faculty review", body: "Per question: marks, the student's answer as read, feedback and the criteria breakdown. Edit any mark." },
      { title: "Release annotated scripts", body: "Students receive their checked script as a PDF, with notes explaining each deduction." },
    ],
    outcomes: [
      "One rubric applied identically across every script",
      "Written reasons on the script for every deduction",
      "Faculty time spent on moderation, not first reading",
      "Unreadable scripts flagged, never guessed",
    ],
    example: { copies: 240, pages: 10, label: "a 240-student course, 10-page scripts" },
    faqs: [
      { q: "Does it handle equations and numerical working?", a: "Yes for written maths and working: pages are read by a vision model, and unclear maths lines get a second read by a dedicated equation reader. Diagrams and graphs are judged by their labels and written explanation, not as drawings, so review those questions yourself." },
      { q: "How long can a script be?", a: "Scripts up to 40 pages are read in full. Each upload accepts files up to 60 MB." },
      { q: "Can we export marks?", a: "Marks are stored per question in the assessment and appear in its reports alongside the checked script. Talk to us about the exact export you need for your ERP." },
    ],
  },
  {
    slug: "exam-boards",
    label: "Exam bodies & large-scale tests",
    icon: "Building2",
    title: "AI-Assisted Evaluation for Exam Bodies and Large-Scale Tests",
    description: "Add an AI first evaluation to large-scale written exams: one rubric per question, consistent annotations, human review before results, and per-page pricing.",
    eyebrow: "For exam bodies & assessment providers",
    h1: "A consistent first evaluation for every script.",
    lede: "When tens of thousands of scripts go to hundreds of evaluators, consistency is the hard part. Evalezy applies one rubric per question to every script and annotates it, so your evaluators review rather than start from scratch.",
    pains: [
      { title: "Evaluator variance", body: "Different evaluators read the same answer differently, and the variance shows up in re-evaluation requests." },
      { title: "Tight result timelines", body: "Results are promised by a date; evaluation capacity is fixed." },
      { title: "Audit trail", body: "When a mark is challenged you need to show what was read, which criteria applied and who changed what." },
    ],
    workflow: [
      { title: "Rubric per question", body: "Your marking scheme becomes criteria that add up to each question's marks." },
      { title: "AI first evaluation", body: "Each script is read, located question by question, and marked in half-mark steps against the criteria." },
      { title: "Human review", body: "Evaluators see the extracted answer, the AI's marks and reasons, and change marks where they disagree. Their edits are recorded and never overwritten." },
      { title: "Release", body: "Results are released only when your team says so." },
    ],
    outcomes: [
      "Identical criteria applied to every script",
      "Per-question record: what was read, the marks, the reasons, who edited",
      "Unreadable scripts routed back, not guessed",
      "Per-page pricing that scales with volume",
    ],
    example: { copies: 10000, pages: 12, label: "10,000 candidates, 12-page scripts" },
    faqs: [
      { q: "Can Evalezy handle our volume?", a: "Current shared capacity checks about 100 copies in 2 to 3 hours. For large-scale exams we plan capacity with you before the exam window; talk to us with your script count and dates." },
      { q: "Do you replace human evaluators?", a: "No. Evalezy does the first evaluation and annotates the script; your evaluators review and own the final mark. Nothing is released without a person pressing release." },
      { q: "Is there an API?", a: "Yes. With the Evaluation API your own system creates the exam and its rubrics, uploads each script as a PDF (one per candidate, up to 50 MB; scripts are uploaded, not fetched from a URL) and reads back question-wise marks with reasons, a needs_review flag and the annotated script. Marks stay drafts until you finalize them. Each institute has a daily copy quota that we set with you; ask us to raise it well before your exam window. Full reference at docs.evalezy.com." },
    ],
  },
  {
    slug: "edtech-platforms",
    label: "Edtech platforms & developers",
    icon: "Code2",
    title: "Handwritten Answer Evaluation API for Edtech Platforms",
    description: "Add AI answer checking to your app or ERP: create an exam, upload each answer sheet as a PDF or send typed answers, then read question-wise marks and the red-pen checked copy.",
    eyebrow: "For edtech platforms & developers",
    h1: "Handwritten answer checking, as an API.",
    lede: "Your learners write on paper; your product lives online. Create the exam through the API, upload each answer sheet as a PDF (or send typed answers), and get back question-wise marks, reasons, feedback and the checked copy in red pen. Marks stay drafts until you finalize them.",
    pains: [
      { title: "OCR alone fails on handwriting", body: "Printed-text OCR cannot read student handwriting, and a grader fed garbage text invents answers." },
      { title: "A score is not a product", body: "Learners want to see their own page marked up, not a JSON blob turned into a table." },
      { title: "Building it in-house is a project", body: "Page reading, answer location, rubrics, consistency, annotation, retries and a review screen for teachers are each a project of their own." },
    ],
    workflow: [
      { title: "Create the exam", body: "POST /exams with the questions as JSON: max marks, answer keys for objective questions, and a rubric or model answer for each long answer." },
      { title: "Upload each copy", body: "One PDF per candidate, up to 50 MB, through presigned upload URLs (1 to 100 files per call). Typed tests send the answers as text instead." },
      { title: "Submit and follow", body: "Submit each copy against your own candidate id. You get 202 and a fixed-price quote at once; poll the submission, or the updated_since feed for many." },
      { title: "Read, review, finalize", body: "Question-wise marks with reasons, feedback, confidence, needs_review and the checked copy PDF. Teachers review in your app or the Vacademy dashboard; then you finalize." },
    ],
    outcomes: [
      "Question-wise marks, criteria with reasons, feedback and confidence in JSON",
      "The student's own copy checked in red pen, as a PDF to show learners",
      "A needs_review flag on the answers a teacher should look at",
      "Teacher review without building a screen: API exams appear in the Vacademy dashboard",
      "₹1 / $0.01 per handwritten page, quoted before grading; failed and cancelled copies are free",
    ],
    example: { copies: 20000, pages: 5, label: "20,000 answer sheets a month, 5 pages each" },
    faqs: [
      { q: "How do I get API keys?", a: `We switch the Evaluation API on for your institute: write to ${SALES_EMAIL} or request access on the demo page with your expected monthly volume. An institute admin then creates keys in the Vacademy dashboard (Settings → Integrations → API keys), each with only the scopes it needs. There is no sandbox: every key is live and every graded copy is billed.` },
      { q: "Is it synchronous?", a: "No. A handwritten copy usually takes a few minutes, so grading is asynchronous: the submit call returns 202 straight away with the submission id, its place in the queue, an estimated ready time and the fixed price. Poll GET /submissions/{id}, or the GET /submissions?updated_since= feed when many copies are in flight. Webhooks are not available yet." },
      { q: "What do I get back?", a: "The status and totals, and for each question: marks awarded out of the maximum, each rubric criterion with its marks and reason, feedback, the answer as read, a confidence score and a needs_review flag. For handwritten copies, GET /submissions/{id}/checked-copy returns the red-pen PDF. Marks are drafts until you call finalize." },
      { q: "What can I send?", a: "Handwritten copies as PDFs only, one per candidate, up to 50 MB; phone photos must be combined into a PDF first, and the API does not yet split a bundled scan or match copies by name. Copies up to 40 pages are graded normally; 41 to 80 pages are graded and flagged for review. Typed tests send each answer as plain text. Questions go in as JSON, not as a question-paper PDF. English answers only for now." },
      { q: "How is the API priced?", a: "1 credit per page of a handwritten PDF, blank pages included, and 1 credit per non-blank typed long answer; objective answers are free. At the standard rate a handwritten page costs ₹1 in India (excluding GST) or $0.01 elsewhere, the same as in the dashboard. The price is fixed and quoted before grading. Failed and cancelled copies are not charged; re-evaluating a copy is charged again. Details at docs.evalezy.com/platform/pricing." },
    ],
  },
];

export const findAudience = (slug: string) => AUDIENCES.find((a) => a.slug === slug);
